include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    await_only_futures: true
    avoid_print: true
    always_declare_return_types: true
    directives_ordering: true
    sort_constructors_first: true

analyzer:
  exclude:
    - build/**
